version: '3'
services:
    web:
        build:
            context: .
            dockerfile: activityOne.dockerfile
        ports:
            - "8080:80"
    webtwo:
        build:
            context: .
            dockerfile: activityThreeWebApp.dockerfile
        ports:
            - "8081:80"
    cache:
        build:
            context: .
            dockerfile: activityTwo.dockerfile
        ports:
            - "80:80"
    loadbalancer:
        build:
            context: .
            dockerfile: activityThreeLoad.dockerfile
        ports:
            - "8082:80"

